name: sonardemo

on:
  push:
    paths:
      - 'myfolder/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean install
        working-directory: myfolder

      - name: Test
        run: echo "Testing is done..."

      - name: Run SonarQube analysis
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=demo \
            -Dsonar.projectName='demo' \
            -Dsonar.host.url=http://54.82.67.126:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        working-directory: myfolder

      #- name: Run SonarQube analysis (with Quality Gate) 
      #  run: | 
      #    mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \ 
      #    -Dsonar.projectKey=demo \ 
      #    -Dsonar.projectName=demo \ 
      #    -Dsonar.host.url=http://54.82.67.126:9000 \ 
      #    -Dsonar.token=${{ secrets.SONAR_TOKEN }} \ 
      #    -Dsonar.qualitygate.wait=true 
      #  working-directory: myfolder