name: sonardemo

on:
  push:
    paths:
      - 'venkat_retail/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: venkat_retail

      - name: Test
        run: echo "Testing is done..."

      - name: Run SonarQube analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=demo \
            -Dsonar.projectName='demo' \
            -Dsonar.host.url=http://98.94.95.181:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        working-directory: venkat_retail